### PR TITLE
Use X-Audit-Log-Header when possible

### PR DESCRIPTION
**Pull request by OoLunar**
# Summary
This replaces the depreciated `?reason=test` url query with the now supported `X-Audit-Log-Reason` header. This also adds the `reason` parameter to a few new methods, where it wasn't previously supported in the library.

# Notes
Many of the methods were tested with consistent success. When modifying channel or role positions, these are logged due to us using the incorrect endpoints (see [modify channel positions](https://discord.com/developers/docs/resources/guild#modify-guild-channel-positions) and [modify role positions](https://discord.com/developers/docs/resources/guild#modify-guild-role-positions)).

### CODE REVIEW

**Review by VelvetThePanda — APPROVED** [review]
The formatting as usual blew the diff out of proportion, but otherwise lgtm

**Comment by OoLunar** [comment]
I'm seeing a lot of extra spaces being removed in the diff. Perhaps we should edit the `.editorconfig` and run a `dotnet format`?

**Comment by VelvetThePanda** [comment]
> I'm seeing a lot of extra spaces being removed in the diff. Perhaps we should edit the `.editorconfig` and run a `dotnet format`?

kioshrug

**Comment by VelvetThePanda** [comment]
Gonna merge this an hope for the best

**Pull request merged**
