### PR TITLE
Rewrite `DiscordEmoji` Try* methods to not throw

### PR DESCRIPTION
**Pull request by OoLunar**
# Summary
When passing incorrect input such as `1`, the methods throw due to an incorrect slice.

# Details
Additionally cleans up some logic for readability.

# Changes proposed
- Cleans up DiscordEmoji.cs
- Fixes an `ArgumentOutOfRangeException` caused by 1-2 character inputs.

# Notes
Changes have been tested.

### CODE REVIEW

**Comment by nathan130200** [comment]
Make also an `DiscordEmoji.FromName` overload that just find in emoji map for example static allocation of discord emoji, since discord client instance inside emoji isn't used in anywhere.

**Comment by OoLunar** [comment]
> Make also an `DiscordEmoji.FromName` overload that just find in emoji map for example static allocation of discord emoji, since discord client instance inside emoji isn't used in anywhere.

You're welcome to make the PR as I'm too busy with other things atm

**Comment by nathan130200** [comment]
I did this PR in past, other maintainers on this repository rejected so i had gave up contributing anymore with D#+

**Comment by InFTord** [comment]
изображение
i think you are a lil bit lying

**Comment by InFTord** [comment]
изображение
or maybe not, but i haven't found anything that you did
did you deleted your D#+ repo and your issue/PR? (if that's even possible)

**Comment by VelvetThePanda** [comment]
The closest PR you've opened was https://github.com/DSharpPlus/DSharpPlus/pull/786

**Comment by nathan130200** [comment]
Yeah and like i've said in #786 who is working an bot to discord must know you are doing. 

The `DiscordEmoji` implicit operator is not an problem for standard emojis, if you call `FromName` with an invalid emoji this will throw exception the same way as implicit operator for common discord emojis.

So instead of me arguing with someone who thinks that kids who are using D#+ and developers don't know how to do anything and that everything needs to be explained delicately. I simply deleted the fork with the changes and set it aside. And moved on with my life. No stress and no fights, everyone ends up happy.

**Comment by VelvetThePanda** [comment]
As an addendum to the above, in the linked PR Emzi had valid reasoning against the addition, even if of questionable influence. 

Your behavior in this thread has rapidly degraded to the beratement of maintainers over trivial matters, which is something we've had to deal with in the past before with a contributor, and don't take to kindly. 

On the behalf of the organization, you're no longer welcome here.

**Pull request merged**
