### PR TITLE
Add permissions property to DiscordMember

### PR DESCRIPTION
**Pull request by VelvetThePanda**
That's literally all I did.

### CODE REVIEW

**Comment by Neuheit** [comment]
What's the reasoning for this?

**Comment by VelvetThePanda** [comment]
> What's the reasoning for this?

Something that comes up more often than I'd like in `#support` on the Discord is "how do I get a member's permissions".

**Comment by Neuheit** [comment]
Has this been tested?

**Comment by VelvetThePanda** [comment]
> Has this been tested?

Same code as PermissionsFor(DiscordMember), so, yes?

**Comment by Neuheit** [comment]
[This code looks very different.](https://github.com/DSharpPlus/DSharpPlus/blob/888947213f91f413dab3624652d3b2f172134c48/DSharpPlus/Entities/Channel/DiscordChannel.cs#L737)

**Comment by IDoEverything** [comment]
this should account for administrator, owner and @everyone permissions as well

**Review by IDoEverything — APPROVED** [review]

**Review by Neuheit — APPROVED** [review]

**Pull request merged**
