### PR TITLE
trace logging runtime toggles

### PR DESCRIPTION
**Pull request by akiraveliara**
As per [this vote](https://canary.discord.com/channels/379378609942560770/379386730538860554/1282614751737675841), implements feature switches for disabling some trace logs and for redacting tokens, IDs, usernames and message contents automatically.

### CODE REVIEW

**Review by InFTord — APPROVED** [review]
docs-wise, LGTM.

**Review by OoLunar — APPROVED** [review]
Any specific reason we're using `AppContext` instead of `DiscordConfiguration`?

**Comment by akiraveliara** [comment]
to make sure the app host can always control them independently of the app author

**Review by Plerx2493 — APPROVED** [review]
LGTM - Maybe we should add to the docs that this can have performance inpact because of the regexes

**Comment by OoLunar** [comment]
Because the Regexes are compiled - converted to C# code at compile-time instead of using a Regex engine at runtime - the perf impact should be negligible imo.

**Comment by akiraveliara** [comment]
the token regex is pretty cheap, the data anonymization less so, but that's already documented as being a suboptimal default.

any objections to merging?

**Comment by OoLunar** [comment]
LGTM

**Pull request merged**
