### PR TITLE
Fixes command 'addsimple' in TestBotDynamicCommands.

### PR DESCRIPTION
**Pull request by theRaphnika**
Fixes command 'addsimple' in TestBotDynamicCommands.

# Details
CommandOverloadBuilder only takes non static methods, therefor both methods have been moved outside of AddSimple.

# Changes proposed
* Changed Methodname to comply with Codeconvention
* moved Fun0 and Func1 out of AddSimple

### CODE REVIEW

**Comment by Emzi0767** [comment]
The builder takes any method and introspects it to build a proper module out of it. There is nothing wrong with the test bot.

**Comment by theRaphnika** [comment]
compiling it and testing it turns out it does not work

**Comment by Emzi0767** [comment]
Worked on my machine when I was originally testing the builder

**Comment by theRaphnika** [comment]
Please test it again. I just tried it without changing anything. It throws following exception:
System.ArgumentException occurred when executing addsimple.
Specified method is not suitable for a command. (Parameter 'method')

**Pull request closed without merging**
