### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AnastasiaLusta**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Fixes #issue/Resolves #issue/Implements functionality. Short description of changes.

# Details
You can put detailed description of the changes in here.

# Changes proposed
* Outline
* Your 
* Changes
* Here

# Notes
Any additional notes go here.

### CODE REVIEW

**Comment by ExaInsanity** [comment]
Did you mean to open this pull request? also, you should probably reset your bot's token.

**Comment by AnastasiaLusta** [comment]
• Track listening
• Entertainment games 
• Option of default promo endings to all bot messages 
• Block list
• Command info
• Gretting

**Comment by ExaInsanity** [comment]
This is a library for bots, not a bot. These features are out of scope here. 
Did you perhaps mean to open a pull request to a branch on your fork?

**Comment by OoLunar** [comment]
Locking and closing this PR for the second time. If you open up the PR again, you will be blocked from the repo.

**Pull request closed without merging**
