### PR TITLE
Adds missing discord audit logs entries

### PR DESCRIPTION
**Pull request by Kiritsu**
# Summary
This implements latest added discord audit logs types.

### CODE REVIEW

**Comment by Kiritsu** [comment]
I have no idea how to properly test/implement integration audit log actions

**Comment by Kiritsu** [comment]
I tried something following official docs TM, I cannot test it.

**Comment by Kiritsu** [comment]
Other audit log entries have been tested properly.

**Comment by Emzi0767** [comment]
Is this merge-ready?

**Comment by Kiritsu** [comment]
Yes!

**Pull request merged**
