### PR TITLE
Improving SlashCommandsExtension 

### PR DESCRIPTION
**Pull request by Plerx2493**
##Summary
Adding additional context in exceptions thrown when registering command methods. Also add the return type check from https://github.com/DSharpPlus/DSharpPlus/pull/1472 to sub methods for command groups

Moved Pr #1473 to right branch

### CODE REVIEW

**Comment by Plerx2493** [comment]
I would like to also add additonal information in exceptions thrown from ParseParameter but it only gets the parameters not the MethodInfo. Maybe we could change it to methodinfo and strip the context parameter in there and dont do it before each invokation?
@OoLunar what are your thoughts?

**Comment by OoLunar** [comment]
> @OoLunar what are your thoughts?

Head empty

**Comment by Plerx2493** [comment]
> I would like to also add additonal information in exceptions thrown from ParseParameter but it only gets the parameters not the MethodInfo. Maybe we could change it to methodinfo and strip the context parameter in there and dont do it before each invokation? @OoLunar what are your thoughts?

ok, next time i should check which branch i checked out. in this branch its already pointed out which method is throwing the exception.

Should be ready to merge

**Comment by OoLunar** [comment]
LGTM, thanks for contributing o7

**Pull request merged**
