### PR TITLE
Fix Grammar

### PR DESCRIPTION
**Pull request by quinchs**
## Summary
This PR adds a missie wissie period to the end of a summarrie wummarie taggie waggi uwu.

This is my frist PR can you pwease merge it owo

### CODE REVIEW

**Review by RGBCube — APPROVED** [review]
such pr very improvement

**Comment by OoLunar** [comment]
https://github.com/DSharpPlus/DSharpPlus/blob/master/CONTRIBUTING.md

**Comment by Naamloos** [comment]
don't ever talk like that again or I am banning you off the repo

**Comment by Naamloos** [comment]
( joke )

**Comment by quinchs** [comment]
> don't ever talk like that again or I am banning you off the repo

Im sowwy i juwst wawnt tuwu hewp the open souwce discowd community uwu

**Comment by VelvetThePanda** [comment]
Quin I love you but I will not hesitate to ship you to Poland

**Pull request merged**
