### PR TITLE
un-annotate DiscordMessage.Content

### PR DESCRIPTION
**Pull request by akiraveliara**
after some deliberation i agree with lunar that throwing this ? here is a bit much for the very rare partial message - the pains of entities as models :^)

### CODE REVIEW

**Comment by Plerx2493** [comment]
Not sure about the annotations with `Components` and `Embeds`. Discord sends `[]` for both on a message which contains neither

**Comment by akiraveliara** [comment]
Components is optional per docs, embeds shouldn't be annotated? let me check again

**Comment by akiraveliara** [comment]
```cs
/// <summary>
/// Gets embeds attached to this message.
/// </summary>
[JsonIgnore]
public IReadOnlyList<DiscordEmbed> Embeds
    => this._embeds;

[JsonProperty("embeds", NullValueHandling = NullValueHandling.Ignore)]
internal List<DiscordEmbed> _embeds = [];
```

**Comment by Plerx2493** [comment]
Then nevermind :when:

**Comment by akiraveliara** [comment]
ready to merge as far as i'm concerned, then

**Pull request merged**
