### PR TITLE
Improve DiscordMember converter

### PR DESCRIPTION
**Pull request by IDoEverything**
# Summary
Improves CommandsNext's `DiscordMember` converter to use the search members endpoint

### CODE REVIEW

**Comment by IDoEverything** [comment]
doesn't work yet, probably should've tested. The search endpoint itself seems to not work (velvet bad?)

**Comment by IDoEverything** [comment]
Should merge after #927 is merged

**Comment by VelvetThePanda** [comment]
> doesn't work yet, probably should've tested. The search endpoint itself seems to not work (velvet bad?)

Worked in testing.

**Comment by IDoEverything** [comment]
> > doesn't work yet, probably should've tested. The search endpoint itself seems to not work (velvet bad?)
> 
> Worked in testing.

The endpoint itself works, but trying to access any of the user properties threw an exception because it depends on user cache

**Comment by VelvetThePanda** [comment]
> > > doesn't work yet, probably should've tested. The search endpoint itself seems to not work (velvet bad?)
> > 
> > 
> > Worked in testing.
> 
> The endpoint itself works, but trying to access any of the user properties threw an exception because it depends on user cache

**Review by Neuheit — APPROVED** [review]
LGTM, once it's out of draft it will be merged.

**Pull request merged**
