### PR TITLE
Fixed DM Channels being null on API requests

### PR DESCRIPTION
**Pull request by DWaffles**
# Summary

As @cmsteffey brought up in #lib-discussion, any API request for messages within a DM returns messages with null channels. This fixes that. 

# Details
Modified `PrepareMessage()` in DiscordApiClient to check if the prepared message channel is null and construct channel objects from there. 

The code is largely ~~stolen~~ based off `UpdateMessage()` in DiscordClient. I'm not sure why GuildId isn't set either for the base channel in the original code, but if it isn't broke don't fix it.
https://github.com/DSharpPlus/DSharpPlus/blob/4281c5911997008400522111287e0b661a000d41/DSharpPlus/Clients/DiscordClient.cs#L776-L791

# Notes
I've done light testing and nothing is broken, at least with, `GetMessagesAsync()`, `GetMessageAsync()`, creating messages via builder or content, `GetPinnedMessagesAsync()`, and `ModifyAsync()`.

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
> API request for messages within a DM returns messages with null channels.

This is intentional* behavior as of Discord's API V8, in which REST requests and I believe GW events don't send channel objects. There used to a patch for this, but I don't know if it was removed or broke. cc @Neuheit

**Comment by VelvetThePanda** [comment]
Actually now that I think about it, I helped fix this too, but I forget where that code sits

**Comment by DWaffles** [comment]
> Actually now that I think about it, I helped fix this too, but I forget where that code sits

I did a decent dive into the code for the API requests but didn't find anything that seemed to relate to setting channels. If that code is still there but partially broken, I can take a look at it if you find it.

**Review by Neuheit — COMMENTED** [review]
LGTM

> I'm not sure why GuildId isn't set either for the base channel in the original code, but if it isn't broke don't fix it.

Feel free to add this if you wouldn't mind, not sure why I didn't have it on the `DiscordClient` code either.

**Comment by DWaffles** [comment]
> Feel free to add this to here and the original code if you wouldn't mind, not sure why I didn't have it on the `DiscordClient` code either.

Done @Neuheit. 

One thing to note: I've looked into the raw json for each message that `PrepareMessage()` gets and I can't find a case where `guild_id` is with the json. I've still made the change however if there's a case where the json includes it.

**Pull request merged**
