### PR TITLE
Correctly match remote and local commands and fix some error messages

### PR DESCRIPTION
**Pull request by Plerx2493**
# Notes
Tested

### CODE REVIEW

**Review by akiraveliara — APPROVED** [review]
tested?

**Comment by Plerx2493** [comment]
Yes, but i wanted to ask the reporting user also to make sure i havent overlooked smth

**Comment by Plerx2493** [comment]
diff is a bit weird because i reused the old branch

**Comment by Plerx2493** [comment]
Tested by reporting user and rtm

**Pull request merged**
