### PR TITLE
[CommandsNext] Rename _lazyAssMember to _lazyMember (Non-breaking)

### PR DESCRIPTION
**Pull request by Lulalaby**
Idfk who did this

### CODE REVIEW

**Comment by Emzi0767** [comment]
It was I. Admittedly I was young and stupid.

**Comment by Naamloos** [comment]
It was funny in my opinion

**Comment by Lulalaby** [comment]
Indeed, but nothing that should be in there I guess

**Comment by DWaffles** [comment]
I have never been more sad to see a PR merged.

**Comment by Emzi0767** [comment]
Meh, joke has ran its course. And we could use less profanity in the source code :v

**Comment by Naamloos** [comment]
meh

**Pull request merged**
