### PR TITLE
Query string overhaul, add wait=true for webhooks

### PR DESCRIPTION
**Pull request by uwx**
# Summary
This supercedes #440.

# Details
I modified Allan's PR and introduced QueryUriBuilder class instead of the dictionary mess. In addition, that dictionary mess was incredibly inconsistent - there were loads of places in the lib where query strings were hardwired. I replaced all these with QueryUriBuilder usages, which for the most part just makes them more readable. It also saves quite a few Dictionary allocations for the webhook endpoints.

The only places where hardcoded query strings still remain are when the library simply returns a link, say, to an image. For instance:

https://github.com/DSharpPlus/DSharpPlus/blob/5d0fc812ed31b5f5cdab0d1c6e6d55057c43f3b4/DSharpPlus/Entities/DiscordGuild.cs#L841-L842

I left these as-is since there are _so many_ of them and they seem to be very purposefully hardcoded. If you want these to use the query URI builder, let me know.

Additionally, I fixed a bug in `GetCurrentUserGuildsAsync` where the rest ratelimit bucket was dependant on the query parameters. I don't know if the original behavior was intentional, please let me know if so.

I want to hear your opinions, so I'm leaving this PR as a draft for now.

# Changes proposed
* Create QueryUriBuilder
* Patch up hardcoded query URIs into the nicer, cleaner builder format
* Make the parameters of `GetCurrentUserGuildsAsync` not part of the ratelimit bucket

# Notes
Credits to @Kiritsu for doing the hard part.

### CODE REVIEW

**Comment by Emzi0767** [comment]
Is there a reason why this PR is still draft?

**Comment by uwx** [comment]
> Is there a reason why this PR is still draft?

> I want to hear your opinions

1. I don't know if you like this pattern
2. I don't know if you want me to apply it to the vast amount of hardcoded query params for returned URIs
3. I don't know if what I presumed to be a bug in `GetCurrentUserGuildsAsync` is intentional or not

**Comment by uwx** [comment]
Also it's untested because I wrote it at like 4am

**Comment by uwx** [comment]
Alright, I'm a dummy, I just saw you said on the Discord that the bug I found is indeed a bug. I'll mark this as ready once I test it in a bit.

**Comment by uwx** [comment]
Superseded by #517, closing.

**Pull request closed without merging**
