### PR TITLE
Support for new Add To Server button

### PR DESCRIPTION
**Pull request by VelvetThePanda**
This PR adds support for some new fields that were added to applications, such as `custom_install_url` and the nested scope field.

### CODE REVIEW

**Comment by OoLunar** [comment]
The scope of your PR has vastly changed. Your "changed files" used to be 4, now it's 480.

Regardless, PR functions correctly. I get an NRE when a custom url is set, unsure if that's intended.
image

**Comment by OoLunar** [comment]
Please add documentation on the `ApplicationInstallParams` properties. Additionally, is the `Permissions` property meant to be private?

**Comment by VelvetThePanda** [comment]
The documentation of this has [actually gone missing](https://discord.com/developers/docs/resources/application#application-object-application-structure), so I'll be closing this.

**Comment by VelvetThePanda** [comment]
There are lots of undocumented things in the API but considering this is in fact undocumented it’s pretty evident it should not be implemented either. This PR was opened for completeness anyway.

**Pull request closed without merging**
