### PR TITLE
remove deprecated events

### PR DESCRIPTION
**Pull request by InFTord**
Make sure you familiarize yourself with our contributing guidelines.
# Details
Removes deprecated events, that were deprecated for a fair amount of time.

# Notes
Any additional notes go here.

### CODE REVIEW

**Comment by akiraveliara** [comment]
lgtm

**Comment by Plerx2493** [comment]
`APPLICATION_COMMAND_PERMISSIONS_UPDATE` is still [documented](https://discord.com/developers/docs/topics/gateway-events#receive-events) by discord. Idk if its still served

**Comment by InFTord** [comment]
cc @akiraveliara @Plerx2493 
also for some reason sharded client didn't had command permissions update event, but now it has :ioa:

**Comment by Plerx2493** [comment]
The shared client is in general not up to date, i want to take a look at it after my auditlog PR and exams

**Pull request merged**
