### PR TITLE
Added New Events and Endpoint

### LINKED ISSUE #522: Missing INVITE_CREATE, INVITE_DELETE, MESSAGE_REACTION_REMOVE_EMOJI events and Delete All Reactions for Emoji endpoint
# Summary
The newly-added events Invite Create, Invite Delete and Message Reaction Remove Emoji, in tandem with the new Delete All Reactions for Emoji endpoint, have to be added to the library.

# Details
These events were added a few days ago <sup>(ERR: TIME IS RELATIVE)</sup> and are documented in an unmerged PR discordapp/discord-api-docs#1309.

# Notes
These were reported by Talion Oak#0001 and @Quahu.

### PR DESCRIPTION
**Pull request by Neuheit**
# Summary
Fixes #522 by implementing support for these events and endpoint.

# Details
As documented [here](https://github.com/discordapp/discord-api-docs/pull/1309), this PR adds 3 new events:

`InviteCreated` - Fired when an invite is created.

`InviteDeleted` - Fired when an invite is deleted.

`MessageReactionRemovedEmoji` - Fired when all of a specific reaction are deleted.

Additionally, added support for a new endpoint that directly causes the `MessageReactionRemovedEmoji` event, which is `DiscordMessage.DeleteReactionsEmojiAsync(DiscordEmoji)`.

Because invite objects can now be sent via dispatch, I also created an invite cache to more reliably retrieve invites, this does a couple of things: 

1. Allows the InviteDeleted event to possibly return a more detailed object rather than the partial one.
2. Could allow a user to get an invite from the cache, which is modeled by `DiscordGuild.GetInvite(string)`.

Currently, the cache has invites added and removed from their respective events, and added automatically through `DiscordGuild.GetInvitesAsync()`. This change and `DiscordGuild.GetInvite()` may not be necessary, but I figured they may be nice to include.

# Changes proposed
* Added support for the 3 new events.
* Added support for the new endpoint.
* Added a method to delete all reactions from a specific emoji.
* Added a cache for invites.
* Added/modified a couple methods to interact with the invite cache.

### CODE REVIEW

**Comment by Neuheit** [comment]
On another note, should properties like Uses, MaxAge, MaxUses, IsTemporary, etc be made nullable since they could be null when serialized from `INVITE_DELETE`?

**Comment by Neuheit** [comment]
Also, I'm debating whether caching invites is a good idea. Since there is no `INVITE_UPDATE` event, a returned invite from the cache may be outdated.

**Comment by Emzi0767** [comment]
Please resolve build issues and conflicts.

**Comment by Neuheit** [comment]
This is a mess so I'm just going to close this and reopen.

**Pull request closed without merging**
