### PR TITLE
Add support for setting a mobile status

### PR DESCRIPTION
**Pull request by IDoEverything**
# Summary
Adds support for having the bot's status show the mobile icon
image

### CODE REVIEW

**Comment by Neuheit** [comment]
Is this documented?

**Comment by IDoEverything** [comment]
It's not but it's a cool feature to have

**Comment by Neuheit** [comment]
While it is a cool feature, I don't believe that Discord plans to document this status so I will be closing this PR. If that changes feel free to reopen this.

**Comment by Lulalaby** [comment]
Note: I told in the dev guild with advaith and a few others about it.
Even tho it's kind of allowed, they say it's better not to.

**Comment by hapaxant** [comment]
notsobot does this and has done for a while :thinking:
i do not see any harm with this if it were to be implemented...

**Comment by OoLunar** [comment]
We only support documented features, which is why this PR hasn't been merged. Until Discord officially documents and supports mobile statuses for bots, this PR will not be merged.

**Pull request closed without merging**
