### PR TITLE
Fix for #419

### PR DESCRIPTION
**Pull request by Kriste00**
# Summary
Candidate fix for #419 

# Changes proposed
1. Make isConnected verify channel is not null 
2. Make GetConnection return null if not connected

### CODE REVIEW

**Comment by Emzi0767** [comment]
What exactly happened with the connection source?

**Comment by Kriste00** [comment]
I edited it in vs, then uploaded it. But the diff says every line has changed. Idk how to fix that, but you can compare the commit code to the original and see if there are any problems.

**Comment by Emzi0767** [comment]
Says the files are identical. That right?

**Comment by Emzi0767** [comment]
There we go. All nice and fixed.

**Pull request merged**
