### PR TITLE
Ported CommandsNext cooldown attribute to Slash Commands

### LINKED ISSUE #1373: Discord Member IsPending not updating when passing membership screening
Make sure you familiarize yourself with our contributing guidelines.

# Summary
IsPending for DiscordMember does not update after agreeing to the rules via membership screening.

# Details
D#+ does not update IsPending status if user updates it while bot is active.
1. Start Bot.
2. Join the server and IsPending status will be true.
3. Agree to rules via membership screening, IsPending status is still true. (it should be false)

But if you join the server and agree to rules and only the start the bot, IsPending status is false. So it does get the initial info correctly, just fails to update it.

### LINKED ISSUE #1374: Slash Commands Cooldown
I've been wanting to implement a cool down for slash commands but from the [DSharp​Plus.​Slash​Commands.​Attributes](https://dsharpplus.github.io/api/DSharpPlus.SlashCommands.Attributes.html) page in the docs it doesn't seem like it exists - are cooldown attributes not able to be implemented for slash commands or is this just a missing feature?

What's the recommended way to implement per-user cooldowns without a slash command attribute?

### PR DESCRIPTION
**Pull request by OoLunar**
Closes #1374. Untested.

### CODE REVIEW

**Comment by Erisa** [comment]
The attribute for this was lazily copied as `CooldownAttribute` rather than the expected `SlashCooldownAttribute`, as well as `CooldownBucketType`.

This lead to me having to avoid ambiguity by doing the following:
```cs
[DSharpPlus.SlashCommands.Attributes.Cooldown(1, 10, DSharpPlus.SlashCommands.Attributes.CooldownBucketType.User)]
```

Even doing that, it does not work. 

I traced through the stack and found out that the `this._bucket` was being recreated every time the command is called, likely from the following line:
https://github.com/DSharpPlus/DSharpPlus/blob/f1d2fc8f58cca77e7a23502f9768a6215b85de14/DSharpPlus.SlashCommands/Built-in%20Checks/SlashCooldownAttribute.cs#L69

I tried fixing this myself for a while, but it seems I'm in over my head so I don't have any solution for it. `this._buckets` is still empty every time the `ExecuteCheckAsync` is called. It contains no values and thus a new bucket is created each call, resulting in nothing happening.

**Review by Erisa — APPROVED** [review]
It seems to work now.

When you use commands faster than the cooldown it throws `DSharpPlus.SlashCommands.SlashExecutionChecksFailedException` and shows "The application did not respond." in Discord - I assume we are expected to handle this exception ourselves, like with others.

Every piece works as expected from my pov.

**Comment by OoLunar** [comment]
Yeah the user is expected to handle that failed check

**Review by ExaInsanity — APPROVED** [review]
generally, looks good to me. 
there are a few things somewhat bothering me (such as `null1` and `null2` as variable names - or whatever is happening name-wise in `ExecuteChecksAsync`, for that matter), and of course, this is currently not applicable to context menu commands, something we might want to tackle in the slashie cleanup branch.

**Comment by Nenkai** [comment]
This PR disregards different commands entirely;

Setting a command with a cooldown i.e with `[SlashCooldown(1, 20, SlashCooldownBucketType.Guild)]` _then_ using another command with the same cooldown within the time span of the first command will fail the check. Is this intended?

**Comment by OoLunar** [comment]
Uh oh. Could you create an issue with a repro?

**Pull request merged**
