### PR TITLE
[ci skip] Fix capitalisation of Git and GitHub

### PR DESCRIPTION
**Pull request by JMcB17**
# Summary
Fixes capitalisation of Git and GitHub in https://dsharpplus.github.io/articles/hosting.html

# Details
GIT -> Git    
Github -> GitHub

# Notes
I would also suggest that, unlike Glitch and Repl.it, Heroku is actually ok for hosting bots and other non-web processes. I've been using it for years to host a bot with no issues and no hacks to keep it alive.    
However it's not significant enough to open an issue for so I'll just put it here.

### CODE REVIEW

**Comment by Emzi0767** [comment]
Heroku is not meant for bots. We will not recommend it.

**Comment by Silverdimond** [comment]
> Heroku is not meant for bots. We will not recommend it.

It might not be meant for bots but that doesn't mean it can not be used for that.  
Unlike Glitch or Repl.it, Heroku has worker dynos that can be used for background things that are not web processes.  
If i recall correctly they do not shut down and they keep running without any web traffic until all of the account's dyno hours are consumed.

**Comment by JMcB17** [comment]
I agree, I don't insist that you recommend it but I would suggest that you don't advise against it.

**Comment by Neuheit** [comment]
Looks like you targeted the wrong branch btw, if you want these to be reflected in an active branch then you should create a PR targeting the master branch.

**Comment by Neuheit** [comment]
I'll be fixing the contributing guidelines to reflect this, apologies for the inconvenience

**Pull request merged**
