### PR TITLE
Fix/v4/slashies cleanup

### PR DESCRIPTION
**Pull request by OoLunar**
Rewrites the internals of Slash Commands. There are no public API changes, however a few methods have been Obsoleted with alternatives suggested in the attribute message. Hopefully once this rewrite is done I'll be able to add functionality very similar to CNext, such as retrieving a list of registered commands.

Help Wanted: Please review my code or optionally make a PR to the `fix/v4/slashies-cleanup` branch with your new code.

EDIT: Closes #1222 due to internal breaking changes.

### CODE REVIEW

**Comment by OneYellowLemon** [comment]
[dbb94db](https://github.com/DSharpPlus/DSharpPlus/pull/1362/commits/dbb94db42c1823a4720723317dab735fa4d9ac8f) broke URLs, should probably be fixed. Should I submit a PR or is that too minor?

**Comment by OoLunar** [comment]
I have it fixed locally, dw

**Comment by OoLunar** [comment]
f66f9cf1bb495246b17652d3ed188651466487fc is a breaking change

**Comment by ExaInsanity** [comment]
i feel a strong urge to fix that

**Comment by OoLunar** [comment]
It was done so that it can be correctly casted to `LifetimeService`- actually you're right it can be fixed

**Comment by Tawmy** [comment]
Does this close #1367 as mentioned in that comment of yours, @OoLunar? Just making sure it's not being forgotten about.

**Comment by OoLunar** [comment]
I can't say I remember explicitly patching it, however this PR isn't finished (hence the draft). When I pick this PR back up, I'll take a look

**Comment by Tawmy** [comment]
How's the exact status of the PR anyways? Do you want it to be tested now or would you like to work on it before testing begins? If the prior I can probably make some time today or tomorrow to do some testing.

**Comment by OoLunar** [comment]
Tests very much need to be done. As far as I remember, registering custom converters and all application command types is all that's required. Make sure you run them too as parameter resolving was reworked. Nullable and enums should work as intended, but if you want to test those too, go at it

**Comment by Tawmy** [comment]
### QA [WIP]:

**Command types:**

- User context menu
- Message context menu
- Slash commands

**Converters for slash commands:**

- Boolean
  - Non-nullable
  - Nullable
  - Nullable with optional value
- Byte
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordAttachment
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordChannel
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordEmoji
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordMember
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordMessage
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordRole
  - Non-nullable
  - Nullable
  - Nullable with optional value
- DiscordUser
  - Non-nullable
  - Nullable
  - Nullable with optional value
- Double
  - Non-nullable
  - Nullable
  - Nullable with optional value
- Enum
  - Choice attribute
    - Non-nullable
    - Nullable
    - Nullable with optional value
  - Directly through enum
    - Non-nullable
    - Nullable
    - Nullable with optional value
  - ChoiceProvider
    - Non-nullable
    - Nullable
    - Nullable with optional value
- Int16
  - Non-nullable
  - Nullable
  - Nullable with optional value
- Int32
  - Non-nullable
  - Nullable
  - Nullable with optional value
- Int64
  - Non-nullable
  - Nullable
  - Nullable with optional value
- SByte
  - Non-nullable
  - Nullable
  - Nullable with optional value
- String
  - Non-nullable
  - Nullable
  - Nullable with optional value
- TimeSpan
  - Non-nullable
  - Nullable
  - Nullable with optional value
- UInt16
  - Non-nullable
  - Nullable
  - Nullable with optional value
- UInt32
  - Non-nullable
  - Nullable
  - Nullable with optional value
- UInt64
  - Non-nullable
  - Nullable
  - Nullable with optional value

**Comment by OoLunar** [comment]
Bless your heart

**Comment by Tawmy** [comment]
### QA Results [WIP]

- Global application commands are broken (guildId null)
  - Workaround: Pass 0 to the method instead

**Pull request closed without merging**
