### PR TITLE
Add limits on slash command entities

### PR DESCRIPTION
**Pull request by IDoEverything**
# Summary
Adds some (more) limits on slash command entity strings

### CODE REVIEW

**Comment by Neuheit** [comment]
Discord states that names must be matched by the regex `^[\w-]{1,32}$`. Since I didn't design this, would it be possible to incorporate/change the checks here to incorporate this regex?

**Comment by IDoEverything** [comment]
I've never used regex before, could someone confirm I've done it right?

**Comment by Neuheit** [comment]
> Command names must be lower-case and match the regular expression ^[\w-]{1,32}$. Commands (including sub-commands) with upper- or mixed- case names will be rejected by the API with a HTTP 400 (Bad Request) response.

I tested the regex and it looks like the regex covers both the 32 length limit and the no whitespace requirement, so I think both of those can be removed. However, I think an uppercase check needs to be added separately since the regex doesn't cover that.

**Comment by IDoEverything** [comment]
@Neuheit done

**Review by Neuheit — APPROVED** [review]

**Pull request merged**
