### PR TITLE
Enable nullable annotations for CNext

### PR DESCRIPTION
**Pull request by Kaoticz**
# Summary
This pull requests enables nullable annotations on CNext's csproj file.

# Details
`<Nullable>enable</Nullable>` and `<WarningsAsErrors>Nullable</WarningsAsErrors>` were added to CNext's project file. Changes then were made to the project to either correct or silence the warnings. Some hidden bugs were fixed along the way.

I tried my best to keep the current API as is. Some collections had `null` as their default state, which is considered "surprising behavior" by most developers. Now they default to being empty and code that checked for nulls was changed accordingly.

I've run some of the commands from [DSharpPlus.Test](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.Test) and everything seems to be in order.

# Notes
Is someone currently doing work on [DSharpPlus.SlashCommands](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.SlashCommands)? Cuz I'm planning to do the same there next.

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
> Is someone currently doing work on [DSharpPlus.SlashCommands](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.SlashCommands)? Cuz I'm planning to do the same there next.

@OoLunar is currently rewriting the extension, don't know what the timeline for that is, though.

**Comment by Kaoticz** [comment]
No problem, I can wait until it is completed.

**Comment by OoLunar** [comment]
Apologies for the late CI build, the runner unexpected quit and logging has now been set up to figure out why.

I am currently working on a SlashCommands rewrite due to the sudden increase in attention. The rewrite will include Nullable. I was not aware of `WarningsAsErrors`, however I'll be sure to enable it for the SlashCommands rewrite. An estimation is current not available, however be assured, I am working on it as fast as I can.

**Review by OoLunar — APPROVED** [review]

**Comment by OoLunar** [comment]
LGTM

**Pull request merged**
