### PR TITLE
Multiple VoiceNext Clients

### PR DESCRIPTION
**Pull request by DrewDaPilot**
Fixed support for multiple VoiceNext clients on the same bot.

# Summary
Fixes an issue where VoiceNext does not respect its attached DiscordClient. 

# Details
Replaced line 91 of `VoiceNextExtension` to use `this.Client` instead of `channel.Client as (DiscordClient)`. This fixes an issue where the channel's client may not have been the same client that is associated with the VoiceNext instance, causing the `VoiceDispatch` update to incorrectly connect a different bot to the voice channel.

# Changes proposed
* Fixed a single offending line; line 91 of VoiceNextExtension.

### CODE REVIEW

**Comment by Emzi0767** [comment]
If you're doing that, might be worth throwing the the associated client is not the same as the channel's, as it leads to invalid state.

**Review by Emzi0767 — CHANGES_REQUESTED** [review]
See my comment

**Review by Neuheit — CHANGES_REQUESTED** [review]
Not sure what VideoNext is but this definitely doesn't seem supported by Discord, not to mention  out of scope of this PR.

**Review by uwx — CHANGES_REQUESTED** [review]
This single-line PR is not the place for dumping the code for your userbot.

**Comment by DrewDaPilot** [comment]
Not sure what happened there, some local changes of stuff im working on somehow ended up in the PR. I will fix this one liner PR to correctly get the appropriate channel snowflake from the correct client and be done with this PR. Sorry for the delays.

**Comment by Neuheit** [comment]
Closing this due to inactivity, feel free to reopen this if you still want to implement this.

**Pull request closed without merging**
