### PR TITLE
Mentionables

### PR DESCRIPTION
**Pull request by Lachee**
# Summary
Added support for Mentionables

# Details
Adds support for Discord's new mentionables. https://discordapp.com/developers/docs/resources/channel#allowed-mentions-object

# Changes proposed
* Created new DiscordMentions object for internals
* Created new IMention. UserMention, RoleMention and EveryoneMention extend this.
* Updated CreateMessage and UploadFiles internals and usages to support `IEnumerable<IMention>`

# Notes
Tested and it works. There is a edge case to account for:
If a user says they want to whitelist a specific user AND allow all user mentions.
The discord API will throw a bad request if this is sent. I am currently just ignoring the specific whitelist and assuming the user actually wanted the allow all user mentions. Is this the best case?

### CODE REVIEW

**Comment by Lachee** [comment]
This will need to be added to webhooks too I suppose

**Comment by Lachee** [comment]
What is the best way to handle the following:
Parse and User/Role options are mutually exclusive and will throw validation errors if both are present. The current solution implemented by commit bd130c8443b1aba88e2e682beaaf4897989d50ab was to ignore the user/role whitelist if their global parse was present instead. (I wish discord just allowed for IDs as 0 for "everyone"). 

We may want to throw an exception if we detect both Parse and User/Roles present, or we could just let it throw the 400: Bad Request.

**Comment by Emzi0767** [comment]
I'll put this as on hold for (reason being, it's not yet finalized) now so that nobody accidentally merges this.

**Comment by Lachee** [comment]
Tested it and it works. Updated the notes in original PR.

**Comment by Emzi0767** [comment]
Interface looks OK. I wonder how long until we have to switch to a message builder 😔.

**Pull request merged**
