### PR TITLE
Integrate Sticker AuditLog objects

### PR DESCRIPTION
**Pull request by Lulalaby**
+ fix of GUILD_STICKER_UPDATED in DiscordShardClient
It was missing

### CODE REVIEW

**Comment by Lulalaby** [comment]
https://github.com/DSharpPlus/DSharpPlus/pull/1007/files#diff-5a969603b5fbbd2bec941b70894fb546e0e5f57d7ae22ca6e640889f70f56dfcR1837
https://github.com/DSharpPlus/DSharpPlus/pull/1007/files#diff-5a969603b5fbbd2bec941b70894fb546e0e5f57d7ae22ca6e640889f70f56dfcR1846

These two seems not to resolve right

I need help with it

**Comment by Lulalaby** [comment]
C:\projects\dsharpplus\DSharpPlus\Entities\Channel\Message\DiscordMessageSticker.cs(127,66): warning CS8524: The switch expression does not handle some values of its input type (it is not exhaustive) involving an unnamed enum value. For example, the pattern '(DSharpPlus.Entities.StickerFormat)0' is not covered. [C:\projects\dsharpplus\DSharpPlus\DSharpPlus.csproj]
C:\projects\dsharpplus\DSharpPlus\Clients\DiscordShardedClient.Events.cs(243,73): warning CS0649: Field 'DiscordShardedClient._guildStickersUpdated' is never assigned to, and will always have its default value null [C:\projects\dsharpplus\DSharpPlus\DSharpPlus.csproj]

**Comment by Lulalaby** [comment]
The rest is good to go

**Review by Naamloos — COMMENTED** [review]
Looks good, but I am not 100% sure on how the other audit log events are implemented. Looks fine if this is comparable.

**Comment by Lulalaby** [comment]
> 
> 
> Looks good, but I am not 100% sure on how the other audit log events are implemented. Looks fine if this is comparable.

I sticked to the default way of implementation.
And I tested it multiple times.

**Pull request merged**
