### PR TITLE
Remove modify embed suppression endpoint

### PR DESCRIPTION
**Pull request by IDoEverything**
# Summary
Removes the modify embed suppression endpoint which has been removed in api v9.

# Details
Removed the `DiscordApiClient` method and added the `flags` property to edit message

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
Shouldn't this be labeled as on-hold?

**Comment by IDoEverything** [comment]
This works in v8 as well, nothing wrong with future-proofing.

**Comment by Neuheit** [comment]
Since we follow by versioning we would want to mark it as obsolete rather than just removing it.

**Comment by IDoEverything** [comment]
> Since we follow by versioning we would want to mark it as obsolete rather than just removing it.

I've only removed the internal `DiscordApiClient` method, and made the public methods edit the message with the flag instead. There shouldn't be any need to mark anything as obsolete.

**Comment by Neuheit** [comment]
> I've only removed the internal `DiscordApiClient` method, and made the public methods edit the message with the flag instead. There shouldn't be any need to mark anything as obsolete.

Yeah I misread that my mistake, Ideally we would want to mark the `ModifyEmbedSuppressionAsync` method as obsolete then. Also wouldn't it be better to have the flag editing be a property on the builder rather than a new parameter for those methods?

**Comment by IDoEverything** [comment]
I did consider that, but since it isn't something you can send when creating a message, it felt more appropriate to me for it to be another parameter.

**Review by Neuheit — APPROVED** [review]

**Pull request merged**
