### PR TITLE
Add ban pagination

### PR DESCRIPTION
**Pull request by OoLunar**

### CODE REVIEW

**Review by VelvetThePanda — APPROVED** [review]
lgtm

**Comment by OoLunar** [comment]
Forgot to say that it was tested with https://github.com/OoLunar/dsharpplus_ban_pagination in a server with 670k+ bans

**Review by ExaInsanity — APPROVED** [review]

**Comment by VelvetThePanda** [comment]
As usual if this breaks off to Poland with you

**Comment by OoLunar** [comment]
If it breaks after being tested in a server with that large of a ban count then I'm going to blame Discord and say v4 code is flawless

**Pull request merged**
