### PR TITLE
Change the visibility of the event error handler to let custom extensions have proper error handling

### PR DESCRIPTION
**Pull request by feelingnothing**
# Summary
Gives custom extensions way to proper handle exceptions in their packages

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
There's no need for this? This event is refired as [DiscordClient#ClientErrored](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Clients/DiscordClient.Events.cs#L673)

**Comment by VelvetThePanda** [comment]
Furthermore as this is an event *handler* I don't see the point in making it public.

**Comment by feelingnothing** [comment]
> 
> 
> Furthermore as this is an event _handler_ I don't see the point in making it public.

You cannot use `DiscordClient#ClientErrored` in `AsyncEvent` class

**Comment by VelvetThePanda** [comment]
So you're trying to invoke ClientErrored from an extension? That's not how extensions work

**Comment by feelingnothing** [comment]
> 
> 
> So you're trying to invoke ClientErrored from an extension? That's not how extensions work

I am trying to handle exceptions the right way, and if it is not how they work, why every official extension uses that function to handle exceptions

**Comment by VelvetThePanda** [comment]
They don't. They have their own events.

**Comment by VelvetThePanda** [comment]
ClientErrored is for *Client* exceptions. Exceptions in extensions should be wrapped in their own events.

**Comment by feelingnothing** [comment]
> 
> 
> ClientErrored is for _Client_ exceptions. Exceptions in extensions should be wrapped in their own events.

image
image
image

**Comment by VelvetThePanda** [comment]
[For interactivity:](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.Interactivity/InteractivityEvents.cs)
[CNext](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L998-L1003)
[Slash Command Extension](https://github.com/IDoEverything/DSharpPlus.SlashCommands/blob/master/SlashCommandsExtension.cs#L617-L622)

**Comment by feelingnothing** [comment]
> 
> 
> [For interactivity:](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.Interactivity/InteractivityEvents.cs)
> [CNext](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L998-L1003)
> [Slash Command Extension](https://github.com/IDoEverything/DSharpPlus.SlashCommands/blob/master/SlashCommandsExtension.cs#L617-L622)
bro
https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L171-L172

**Comment by VelvetThePanda** [comment]
Actually, it seems to be exposed to extensions form the looks of it https://github.com/IDoEverything/DSharpPlus.SlashCommands/blob/master/SlashCommandsExtension.cs#L53

**Comment by feelingnothing** [comment]
> 
> 
> Actually, it seems to be exposed to extensions form the looks of it https://github.com/IDoEverything/DSharpPlus.SlashCommands/blob/master/SlashCommandsExtension.cs#L53

thats what im saying, if official packages use them why custom cant

**Comment by VelvetThePanda** [comment]
IDoEverything's extension isn't official.

**Comment by feelingnothing** [comment]
> 
> 
> IDoEverything's extension isn't official.

i didnt say it is official, you pointed me to IDoEverything's extension exception handling line and it is null, but in official extensions they are using function i am trying to make public

**Comment by feelingnothing** [comment]
i do not understand why dsharpplus core needs to share internals with official extensions, this means that something else is impossible too from custom extension, i will look into internals that official extensions use and point some things in discussion because there should not be something impossible to make from custom extension

**Comment by VelvetThePanda** [comment]
What

**Comment by VelvetThePanda** [comment]
> i do not understand why dsharpplus core needs to share internals with official extensions,

You have to add the extension to the client.

**Comment by VelvetThePanda** [comment]
As for the error handler, I dunno.

**Comment by feelingnothing** [comment]
> 
> 
> > i do not understand why dsharpplus core needs to share internals with official extensions,
> 
> You have to add the extension to the client.

yes you are, i did not say you dont have to, why does core share internals with the extensions, why you cant make all internals that extension might use public so any extension can use it?

**Comment by VelvetThePanda** [comment]
cc @Emzi0767 @Neuheit Git Blame says you two were the ones that worked on that event handler, so you're probably more knowledgeable about the justification behind that

**Comment by feelingnothing** [comment]
I will wait for someone to review this PR and will look into internals that official extensions use

**Review by Giggitybyte — COMMENTED** [review]
I suppose the real issue here is that the extension "API" is rather basic; only a `DiscordClient` instance is provided with no way to directly interact with core internals. Because of that, there are limits in how users can *extend* the library.

Perhaps instead of applying this band-aid fix, the extension system as a whole could be improved.

**Comment by VelvetThePanda** [comment]
This is true. Do you have any ideas of what should go into this? I wanna take note :b

**Comment by Neuheit** [comment]
It would be considered abstraction leakage to make this change. Yes, while the official extensions may have access to this method, there are also some extensions (such as lavalink) that have access to internal websocket methods to directly send messages, which we obviously can't make public. I won't be accepting this change however there are a few things you can do to solve your issue: 

1. Create your own error handler method and pass that to your async event constructors
2. Do your logging in the `ClientErrored` event
3. Get the internal event error handler in the client via reflection.

Hope this helps.

**Pull request closed without merging**
