### PR TITLE
[WIP] Edited replies don't change mention state

### LINKED ISSUE #833: Editing a reply message which didn't mention makes it mention
# Summary
If you send a reply message that does not mention, then edit it, it will make it mention. This is not normal behaviour.

# Details
No idea why that is, I reckon @VelvetThePanda and @ProfDoof will have some input as they are the ones who originally implemented the feature in D#+

# Steps to reproduce
```cs
[Command]
public async Task TestReplyBork(CommandContext ctx)
{
    var msg = await ctx.RespondAsync("nope"); // sends a non-mentioning reply by default
    await msg.ModifyAsync(x => x.Content = "yep"); // now it mentions
}
```

# Notes
This has to be resolved before 4.0 release.

### PR DESCRIPTION
**Pull request by CatThingy**
# Summary
Fixes #833.

# Details
Implemented as discussed in https://github.com/DSharpPlus/DSharpPlus/issues/833#issuecomment-817133735 and https://github.com/DSharpPlus/DSharpPlus/issues/833#issuecomment-817133953.

### CODE REVIEW

**Comment by IDoEverything** [comment]
While this fixes replying without a mention, it breaks replying with a mention; now editing a reply with a mention makes it not mention.

**Comment by VelvetThePanda** [comment]
@IDoEverything Seems to work fine? see

**Comment by VelvetThePanda** [comment]
Wait oof wrong test

**Comment by VelvetThePanda** [comment]
But it's still a good sign

**Comment by CatThingy** [comment]
Something is incredly strange with editing replies. Even after hardcoding `pld.Mentions = new DiscordMentions(new IMention[]{UserMention.All, RoleMention.All, EveryoneMention.All, new RepliedUserMention()}, true, true);` in [EditMessageAsync](https://github.com/DSharpPlus/DSharpPlus/blob/21ba17608908b6ef8c478baaf9935d0ee92f31b9/DSharpPlus/Net/Rest/DiscordApiClient.cs#L1198), edited replies never mention.

@VelvetThePanda That showcases a very strange case with this: edited replies only mention if the message body mentions the same person.

**Comment by VelvetThePanda** [comment]
> That showcases a very strange case with this: edited replies only mention if the message body mentions the same person.

Why not just use `Mentions.All`

Also yes, if you mention the author of a reply, you will make it a ping reply (unless explicitly stated otherwise with AllowedMentions). As for why the behavior this PR fixes existed to begin with is beyond me

**Comment by VelvetThePanda** [comment]
> @IDoEverything okay, edits do not mention anymore, and explcitly allowing mentions works as seen here image

Also @CatThingy as you can see here, using the same code from this PR, it works as intended (Yes, passing no mentions by default is intended if you ask me)

**Comment by CatThingy** [comment]
> Why not just use `Mentions.All`

`Mentions.All` does not contain `RepliedUserMention`.

> Also @CatThingy as you can see here, using the same code from this PR, it works as intended (Yes, passing no mentions by default is intended if you ask me)

The unintended part is that replies that mention (without a separate mention inside of them) turn into replies that don't mention on edit.

**Comment by VelvetThePanda** [comment]
> `Mentions.All` does not contain `RepliedUserMention`.

Mentions.All is irrespective of `RepliedUserMention` because `RepliedUserMention` simply states "Mention the reply author regardless of if they're directly mentioned" as you can see above

**Comment by VelvetThePanda** [comment]
Looking at what the client does can save us a *massive* headache sometimes ![](https://cdn.velvetthepanda.dev/3cBRI.png}

**Comment by VelvetThePanda** [comment]
@CatThingy @IDoEverything

**Comment by VelvetThePanda** [comment]
If you want to KEEP mentions, you pass nothing, but if you want to RESTRICT mentions, you have to pass the array

**Comment by VelvetThePanda** [comment]
Ugh. There doesn't appear to be any effective way to fix this because the API is just too limited.

**Comment by VelvetThePanda** [comment]
Turns out this is a [known issue](https://github.com/discord/discord-api-docs/issues/3378) but I don't think Discord has any plans of 'fixing' this.

**Comment by IDoEverything** [comment]
Is there a reason we can't just read the `ReferencedMessage` property, and decide what allowed mentions to include based on that?

**Comment by VelvetThePanda** [comment]
> Is there a reason we can't just read the `ReferencedMessage` property, and decide what allowed mentions to include based on that?

I was tempted to do that, but you can't differentiate between who is and is not mentioned I think

**Comment by VelvetThePanda** [comment]
Okay so: This *would* work, if we didn't, you know **REGEX EVERY MENTION IN A MESSAGE**. God I hate this library's internals sometimes. Anyway, this would require reworking how mentions are handled in general, which is a task I was planning to undergo anyway. the `mentions[]` array Discord sends is empty if you don't pass allowed mentions, but it would also be possible to detect skeleton users (maybe?) and go based on that

**Comment by ProfDoof** [comment]
So, we can probably remove the regex if we want to. I only kept it to maintain backwards compatibility with past behavior.

**Comment by VelvetThePanda** [comment]
Yeah and that's the thing; it *could* break things like the DiscordUser converter, which allow you to use any user mention or id, but I suppose they have their own regex systems. It would be much better to rid it and alert people of a possible breaking change

**Comment by VelvetThePanda** [comment]
@IDoEverything @ProfDoof @CatThingy I think I figured it out. The entire time the issue was with the `DiscordMentions` constructor

**Comment by IDoEverything** [comment]
Is this still being worked on?

**Comment by Lulalaby** [comment]
> Is this still being worked on?
> 

#1054 seems to be a replacement.
This here should probably be closed.

**Comment by VelvetThePanda** [comment]
Gonna close this in lieu of #1054, which addresses this issue and fixes potential bugs with mentions in general.

**Pull request closed without merging**
