### PR TITLE
Clean-up VNext

### PR DESCRIPTION
**Pull request by InFTord**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Reformats VNext, because it looks like very old code.
Also replaces old natives with new natives from [DSharpPlus.VoiceLink](https://github.com/OoLunar/DSharpPlus.VoiceLink)

# Notes
let's pray that git diff isn't trolling us yet again

### CODE REVIEW

**Comment by InFTord** [comment]
@OoLunar

**Comment by OoLunar** [comment]
The DSharpPlus organization has my explicit approval to use or distribute the [`OoLunar.DSharpPlus.VoiceLink.Opus`](https://www.nuget.org/packages/OoLunar.DSharpPlus.VoiceLink.Natives.Opus) and [`OoLunar.DSharpPlus.VoiceLink.Sodium`](https://www.nuget.org/packages/OoLunar.DSharpPlus.VoiceLink.Natives.Sodium/) NuGet packages. The DSharpPlus organization does not have permission to distribute modified copies of the Nuget packages. Instead, they are encouraged to propose their changes on the [original GitHub repository](https://github.com/OoLunar/DSharpPlus.VoiceLink/) or find different packages to use.

**Comment by OoLunar** [comment]
Please resolve conflicts. Has this PR been tested?

**Comment by InFTord** [comment]
> Please resolve conflicts. Has this PR been tested?

Yes, but still if you can - test it, please.

**Pull request closed without merging**
