### PR TITLE
One DiscordWebhook#ExecuteAsync overload is now all mandatory

### PR DESCRIPTION
**Pull request by GreemDev**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
This change prevents "ambiguous reference" compiler errors.

# Details
N/A

# Changes proposed
* Make a single overload on DiscordWebhook#ExecuteAsync all mandatory parameters.

# Notes
N/A

### CODE REVIEW

**Comment by Kiritsu** [comment]
As this method takes a lot of arguments, why not introduce a method that takes an action instead to get rid of the ambiguous reference and get a cleaner method?

**Comment by GreemDev** [comment]
> 
> 
> As this method takes a lot of arguments, why not introduce a method that takes an action instead to get rid of the ambiguous reference and get a cleaner method?

Good point. Not entirely sure how open Naam or Emzi is to doing that though.

**Comment by uwx** [comment]
> > As this method takes a lot of arguments, why not introduce a method that takes an action instead to get rid of the ambiguous reference and get a cleaner method?
> 
> Good point. Not entirely sure how open Naam or Emzi is to doing that though.

A builder type might be better, as the actions are reserved for edit operations. This current solution is just a band-aid fix to get the method working to begin with (it's unusable otherwise) but it lacks the ability to send embeds and multiple files without attaching all the other metadata.

**Comment by Emzi0767** [comment]
This is now superseded by #517.

**Pull request closed without merging**
