### PR TITLE
fix: Sharding broke GDC

### PR DESCRIPTION
**Pull request by VelvetToroyashi**
See commit description 

Explosion emoji

### CODE REVIEW

**Comment by akiraveliara** [comment]
tested?

**Comment by VelvetToroyashi** [comment]
@DubyaDude validated it for the most part

**Comment by akiraveliara** [comment]
define "validated for the most part"

**Comment by VelvetToroyashi** [comment]
We looked at the values in the debugger and it checked out, but I can grab the pr artifact if you want me to triple check

**Comment by VelvetToroyashi** [comment]
Where even are my PR artifacts

**Comment by VelvetToroyashi** [comment]
Actually I've just realized session created is also...questionable at best

**Comment by VelvetToroyashi** [comment]
Tested

**Comment by VelvetToroyashi** [comment]
image
1 and 2 shards both work fine
```cs
client.GuildDownloadCompleted += async (c, e) => c.Logger.LogInformation("Yippee");
```

**Pull request merged**
