### PR TITLE
Fix #1357

### LINKED ISSUE #1357: Disable buttons in pagination
# Summary
Ability to remove/disable buttons in paginated messages
Select whether to disable or remove buttons when only 1 page exists

### PR DESCRIPTION
**Pull request by thunderstorm010**
Not fully implemented for all methods
Fixes #1357

### CODE REVIEW

**Review by VelvetThePanda — CHANGES_REQUESTED** [review]
I feel like this is the wrong way to tackle this. 

Instead, consider making a LINQ query of `Where(btn => btn is not null).ToArray()` for `PaginationButtons#ButtonArray`.

**Comment by VelvetThePanda** [comment]
This PR was marked as a draft, and has been sitting stagnant for six months. Is this in a mergeable state?

**Comment by thunderstorm010** [comment]
Should I make it a normal PR?

**Comment by VelvetThePanda** [comment]
If it's ready to merge yes.

**Comment by thunderstorm010** [comment]
yep I think so

**Pull request merged**
