### PR TITLE
Add nsfw_level to guilds

### PR DESCRIPTION
**Pull request by VelvetThePanda**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Adds enum + docs

# Notes
Don't shoot me emzi. Drafting for now.

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
GitHub claims there's no merge conflicts. Don't know how I managed to screw up my commit history again, but apparnetly this was merged into the DAPI docs, even if the markdown is shot.

**Comment by DWaffles** [comment]
Unless I'm mistaken I believe @Lulalaby put nsfw levels into #890. [Commit here.](https://github.com/DSharpPlus/DSharpPlus/pull/890/commits/b7914fca2f1267a80d5cff6f9b224b9ce77256d5)

Seeing as we don't know when #890 will be merged and this is ready, it might be prudent to undo the nsfw changes in that PR since they're the same changes.

**Comment by Lulalaby** [comment]
> 
> 
> Unless I'm mistaken I believe @Lulalaby put nsfw levels into #890. [Commit here.](https://github.com/DSharpPlus/DSharpPlus/pull/890/commits/b7914fca2f1267a80d5cff6f9b224b9ce77256d5)
> 
> Seeing as we don't know when #890 will be merged and this is ready, it might be prudent to undo the nsfw changes in that PR since they're the same changes.

Yes I did

@VelvetThePanda why the title is still starting with Draft:

And it can be merged, I resolve the conflicts later.

**Comment by Lulalaby** [comment]
CC @Neuheit

**Review by Neuheit — APPROVED** [review]

**Comment by Neuheit** [comment]
There's a conflict that needs to be fixed from the recent merge btw.

**Comment by VelvetThePanda** [comment]
Ack. Cherry-picking commits kinda turned my git tree into a clusterfuck. I'll rebase this tomorrow. Thanks for pointing it out!

**Comment by VelvetThePanda** [comment]
Actually, forgot I can just edit it here on GitHub. Should be ready to go @Neuheit

**Pull request merged**
