### PR TITLE
Reduce VoiceNext's CPU usage with SpinWait

### PR DESCRIPTION
**Pull request by WamWooWam**
# Summary
This PR reduces the overall CPU usage of VoiceNext while receiving audio.

# Details
Uses `System.Threading.SpinWait` to reduce the overall CPU usage of VNext's receive code by spinning the CPU when there's no data to process. In my brief testing, this cuts CPU usage to basically zero, while not sacrificing performance.

# Changes proposed
* I mean I pretty much have already...

# Notes
This may warrant a bit more testing, for me it works perfectly, but others may wanna try this out before any decisions are made.

### CODE REVIEW

**Comment by Emzi0767** [comment]
I'm curious whether it's possible skip spinning altogether and just wait for I/O directly. Maybe the UdpClient allows for something like this?

**Comment by WamWooWam** [comment]
I mean, Googling around, `Receive` is blocking. That might be enough? But could also be inconvenient.

**Comment by uwx** [comment]
"The returned Task&lt;TResult> object will complete after the UDP packet has been received." doesn't that mean that it'll only spin if either voice receive has just started and there is no data yet, or voice decode threw an exception?

**Comment by WamWooWam** [comment]
In theory, it wouldn't need to spin full stop, because Receive blocks, it'll just wait for data to become available by itself, the issue here is, I'm not sure how cancel-able this is, nor if, in the background, it's just spinning anyway like we already are doing here.

I'd probably try to incorporate this, but considering VNext has a rewrite planned, I was going for a quicker fix.

**Comment by WamWooWam** [comment]
wew i fucked up this branch wise

**Pull request closed without merging**
