### PR TITLE
Improving SlashCommandsExtension

### PR DESCRIPTION
**Pull request by Plerx2493**
# Summary
Adding additional context in exceptions thrown when registering command methods. Also add the return type check from #1472 to sub methods for command groups

### CODE REVIEW

**Comment by Plerx2493** [comment]
I also want to add more informations to the exceptions in the parseParameters function but this would require to change the parameters of this method

Function: https://github.com/DSharpPlus/DSharpPlus/blob/4d9e35aa083bf5dbb959f5b6fbe9e83f7980cdb0/DSharpPlus.SlashCommands/SlashCommandsExtension.cs#L407

**Comment by OoLunar** [comment]
Perhaps these changes should be pushed to the [fix/v4/slashies-cleanup](https://github.com/DSharpPlus/DSharpPlus/tree/fix/v4/slashies-cleanup) branch?

**Comment by Plerx2493** [comment]
Oh i forgot you do a revamp. Can i move it some how or can you do it?

**Comment by OoLunar** [comment]
Oh, you'll have to make a new PR

**Comment by Plerx2493** [comment]
New PR is open

**Pull request closed without merging**
