### PR TITLE
Implement Video Quality Mode

### PR DESCRIPTION
**Pull request by DWaffles**
# Summary
Implements voice quality modes for voice channels, as listed in #825.

# Details
Added an enum, ChannelQualityMode, to store the quality modes a channel can have and added that to DiscordChannel. Tried to remain locally consistent with the rest of library with the names and XML comments where possible.

I modified functions that edit or create channels to account for the new property where applicable. I might have missed some, please let me know if I did. 

# Changes proposed
* Added new enum, ChannelQualityMode
* Added enum as parameter to DiscordChannel
* Updated ChannelEditModel 
* Updated `CloneAsync()` and `ModifyAsync()` in DiscordChannel.cs
* Updated `CreateGuildChannelAsync()` and both `ModifyChannelAsync()` methods in DiscordRestClient.cs
* Updated `CreateVoiceChannelAsync() `and `CreateChannelAsync()` in DiscordGuild.cs
* Updated `CreateGuildChannelAsync()` and `ModifyChannelAsync()` in DiscordApiClient.cs
* Updated `OnChannelUpdateEventAsync()` in DiscordClient.Dispatch.cs
* Updated RestChannelCreatePayload and RestChannelModifyPayload classes in RestChannelPayloads.cs

# Notes
* It seems Discord returns a value of 0 for `video_quality_mode` until a voice channel's quality mode setting is touched (not even changed). This is the same value it returns for text channels.
* I have not touched anything relating to audit log or audit log objects (like DiscordAuditLogChannelEntry ) as I do not quite understand how they work. If anyone could give me pointers or advice on this it would be appreciated.
* I've done testing to check that the create and modify methods work as intended, I would appreciate if someone else also tested them on their machine.

### CODE REVIEW

**Comment by Neuheit** [comment]
So right now the issue with this is that since you are adding a parameter in the middle of the method, it is considered a breaking change. We're currently discussing the best way to get around this. 

There are also a few conflicts that have to be resolved.

**Comment by DWaffles** [comment]
@Neuheit regarding the method signature change and how that is considered a breaking change, I understand. I can remove the changes for user facing methods. Essentially, the property is publicly accessible and can be changed via ChannelEditModel unless that is also a breaking change. A user would not be able to change the quality mode via `ModifyAsync` and `ModifyChannelAsync`; nor could they create a channel and specify a video quality mode. 

The conflicts are from the newly committed formatting files. I have looked over the changes and they're syntax related rather than logic.

I apologize regarding any unknowns that arose from this PR, should one my next PRs affect something user facing I will ask a maintainer if that is preferable.

**Comment by Neuheit** [comment]
Yeah it's not your fault. If this was before 4.0 was released we would have merged this. Ideally we would want all of this merged, but we're in the process of discussing how to change the versioning to accommodate this.

**Comment by DWaffles** [comment]
I've went ahead and resolved the merge conflicts, I've tested them as well so they should work fine.

**Comment by Neuheit** [comment]
Can you fix your branch diff as well? Right now it shows over 11,000 line changes.

**Comment by DWaffles** [comment]
Closing this as I opened #888 for this feature.

**Pull request closed without merging**
