### PR TITLE
Update docfx.json

### PR DESCRIPTION
**Pull request by InFTord**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Updates DocFX to latest version+adds one change that makes API docs look a little bit better.

# Notes
did you missed me with those kind of PRs? :)

### CODE REVIEW

**Comment by OoLunar** [comment]
Someday I'm going to start asking for screenshots of a before and after.

**Comment by Plerx2493** [comment]
Would be helpful for reviews ^^

**Comment by InFTord** [comment]
give me one second i don't have docfx and d#+ cloned

**Comment by InFTord** [comment]
image
it will install... any second.....

**Comment by InFTord** [comment]
image
before
image
after

**Review by OoLunar — APPROVED** [review]

**Review by Plerx2493 — APPROVED** [review]

**Comment by Plerx2493** [comment]
> Updates DocFX to latest version
Are you sure this is containted in the pr? i only see the undated docfx settings

**Comment by InFTord** [comment]
it will update when pr is merged

**Comment by OoLunar** [comment]
Testing in production I see :^)

**Comment by InFTord** [comment]
i decided to not care about broken links for now because i'm lazy

**Pull request merged**
