### PR TITLE
Fix env var name

### PR DESCRIPTION
**Pull request by OoLunar**
Fix env var name

It would be great if we could test GH Actions locally.

### CODE REVIEW

**Comment by Naamloos** [comment]
ploopsies

**Comment by InFTord** [comment]
@OoLunar https://github.com/nektos/act :) (for testing GH actions)

**Comment by OoLunar** [comment]
YOU'RE ONLY JUST TELLING ME ABOUT THIS **_NOW???_**

**Comment by InFTord** [comment]
have you tried to use google once in your life? /s

**Comment by InFTord** [comment]
also i literally woke up today to see like 10 commits from you in #commits shush

**Comment by VelvetThePanda** [comment]
> YOU'RE ONLY JUST TELLING ME ABOUT THIS **_NOW???_**

I believe someone's brought it to your attention before, actually

**Pull request merged**
