### PR TITLE
Add support for deleted roles when looking through the audit log.

### PR DESCRIPTION
**Pull request by TheLastTech**
Previously you were handed nulls.

Make sure you familiarize yourself with our contributing guidelines.

# Summary
Fixes the Issue of null audit roles

# Details
Not much, just checked for roles that don't exist.

### CODE REVIEW

**Comment by Emzi0767** [comment]
Please don't PascalCase locals.

**Comment by TheLastTech** [comment]
PascalCase  is life, PascalCase  is love.

I didn't see a style recommendation sorry.

**Comment by TheLastTech** [comment]
I like how you and your people were so rude to me and yet still accept my bug fix. 

Eat that crow, bitch.

**Comment by NaamloosDT** [comment]
@TheLastTech are you fucking blind? I closed your PR because of your rude behaviour and personal harassment towards emzi.

**Pull request closed without merging**
