### PR TITLE
re-add ChannelDeleted

### LINKED ISSUE #1959: Missing HandleChannelDeleted event handler
### Description

I can not find the `HandleChannelDeleted` event, is it used somewhere else?

### Specify the libraries you want this feature request to affect

DSharpPlus, the core library, DSharpPlus.Commands

### Other considerations

_No response_

### PR DESCRIPTION
**Pull request by akiraveliara**
closes #1959

### CODE REVIEW

**Comment by Plerx2493** [comment]
Not sure if we don't implement at all or if it also went missing but currently we don't have all poll events

**Comment by akiraveliara** [comment]
do you have a list?

**Comment by Plerx2493** [comment]
Afaik `MessagePollVoteRemoved` is missing, on mobile rn

**Comment by akiraveliara** [comment]
that one is handled rather questionably in dispatch atm, out of scope imo

**Comment by Plerx2493** [comment]
Ich, ibwill put it on the v5 tracking issue

**Review by Plerx2493 — APPROVED** [review]

**Pull request merged**
