### PR TITLE
update blurple color

### PR DESCRIPTION
**Pull request by InFTord**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Updates blurple color to be up-to-date. (stolen from here https://discord.com/branding btw)
# Notes
do i *really* need to describe this?

### CODE REVIEW

**Comment by akiraveliara** [comment]
@InFTord if you don't mind, please update the other branding colours in this PR too

**Comment by InFTord** [comment]
sure let me update them from my phone /s
(tomorrow)

**Comment by OoLunar** [comment]
...when is tomorrow?

**Comment by akiraveliara** [comment]
tomorrow wasn't yet i'm afraid

**Comment by DubyaDude** [comment]
and tomorrow never came...

**Comment by InFTord** [comment]
sorry i died yesterday (temp 40.0)

**Pull request closed without merging**
