### PR TITLE
Allow `RequireTextReply` on the first parameter

### PR DESCRIPTION
**Pull request by OoLunar**
# Summary
When `RequireTextReplyAttribute` is applied to the first parameter, the command will currently never be able to execute via a text reply due to `TextConverterContext.NextArgument()` always returning `false` since it doesn't check to see if it requests a reply. This is resolved by adding a new `ConverterRequiresText` enum, which allows for more functionality through `ConverterRequiresText.WhenReplyPresent` and `ConverterRequiresText.WhenMissingReply`.

Additionally this renames `TextConverterContext.SwitchToMessage` to `TextConverterContext.SwitchToReply` for further clarity.

# Notes
Tested.

### CODE REVIEW

**Comment by akiraveliara** [comment]
ConverterRequiresText is an... odd naming choice, we typically name types after nouns; and i'm not entirely clear on when an argument converter would not require an argument to convert (the Never option)

**Comment by OoLunar** [comment]
> ConverterRequiresText is an... odd naming choice, we typically name types after nouns

What else would you prefer?

> and i'm not entirely clear on when an argument converter would not require an argument to convert (the Never option)

`DiscordAttachment`s, reading other properties from `DiscordMessage` in general

**Comment by akiraveliara** [comment]
what about ConverterInputType.Text, .None, .TextIfReplyPresent, .TextIfReplyMissing or similar

**Review by akiraveliara — APPROVED** [review]
please fix line endings in EnumArgumentConverter `1.cs

**Review by akiraveliara — APPROVED** [review]

**Pull request merged**
