### PR TITLE
Added missing channel type.

### PR DESCRIPTION
**Pull request by patrickbkt**
Title

### CODE REVIEW

**Comment by OoLunar** [comment]
Please revise the documentation to be more specific as right now it's easily confused with forum channels. Feel free to copy the docs that Discord docs have.

**Comment by Patrickooos** [comment]
this is the official discord doc

**Comment by Patrickooos** [comment]
they simply added "similar to GUILD_FORUM channels"

**Comment by patrickbkt** [comment]
so what's the issue here ? i can't understand why it's not merged

**Comment by akiraveliara** [comment]
documentation is not specific enough; at the very least i'd suggest "indicates that this is a media channel" or something - if the discord docs are bad, we should still provide something usable

**Pull request merged**
