### PR TITLE
Support for `GUILD_JOIN_REQUEST_DELETE`

### PR DESCRIPTION
**Pull request by VelvetThePanda**
# Summary
Adds support for the [vaguely documented](https://github.com/discord/discord-api-docs/pull/3871), and "unreleased" `GUILD_JOIN_REQUEST_DELETE` event that's plagued the consoles of D#+ users for several months now.

# Details
Seeing as this is both "unreleased" and seemingly random (I can't seem to repro even w/ membership screening), testing for this will be limited, if existent at all, but I'll try regardless.

# Changes proposed
- Add switch case for `guild_join_request_delete`
- Add event to regular and sharded client

### CODE REVIEW

**Comment by Lulalaby** [comment]
@VelvetThePanda 

Add GUILD_JOIN_REQUEST_CREATE and GUILD_JOIN_REQUEST_UPDATE too.
They exist and have the same strucutre

**Comment by VerdantOlly** [comment]
Any update on this?

**Comment by akiraveliara** [comment]
it's not documented, we can't implement it until it's documented

**Comment by VerdantOlly** [comment]
Aw, alright. :( Thanks

**Pull request closed without merging**
