### PR TITLE
Add embed character count to message builder and embeds.

### PR DESCRIPTION
**Pull request by loukylor**
# Summary
Adds a check so that the 6000 character limit on embeds is easier to track.

# Details
Right now, there's no easy way to check if you've exceeded the 6000 character limit on message embeds. This should hopefully fix that issue.

# Changes proposed
 * Adds a `CharCount` property to `DiscordEmbed`, `DiscordEmbedField`, `DiscordEmbedFooter`, `DiscordEmbedAuthor`, `DiscordEmbedBuilder`, `EmbedAuthor`, and `EmbedFooter`. 
 * It also adds an `EmbedsCharCount` property to `DiscordMessageBuilder`. 
 * A check to make sure the count does not exceed 6000 is in place for `DiscordEmbedBuilder`'s and `DiscordMessageBuilder`'s property. If the number is exceeded, an `ArgumentException` will throw.
 * The properties only reflect the characters that Discord counts.

### CODE REVIEW

**Comment by IDoEverything** [comment]
I'm not convinced this is particularly useful. You can easily just add up the characters of every field yourself.

**Comment by VelvetThePanda** [comment]
I feel quite the contrary; I'd like to have more concise error messages other than `Bad Request: 400` and having to bloat my code with Chris everywhere. This is especially useful when dealing with multiple embeds, since discord doesn't explicitly state that the TOTAL character count for ALL embeds must be <= 6000 characters

**Comment by uwx** [comment]
Who the fuck is Chris

**Comment by VelvetThePanda** [comment]
LMAO checks* thanks autocorrect

**Comment by loukylor** [comment]
> I'm not convinced this is particularly useful. You can easily just add up the characters of every field yourself.

I do agree that it isn't too difficult to add up the characters yourself, but it sort of leaves the dev thinking: "Why isn't this just built in to the lib?". There's really no reason to not add it as I see it at least. (Given my code actually works, there might be a bug or 2 left to squash)

**Comment by DWaffles** [comment]
> I do agree that it isn't too difficult to add up the characters yourself, but it sort of leaves the dev thinking: "Why isn't this just built in to the lib?". There's really no reason to not add it as I see it at least. (Given my code actually works, there might be a bug or 2 left to squash)

I'm also in favor of this. Yes, it's not difficult. But adding this extra help reduces some of the workload by having to manually do this or have an extension method.

**Comment by IDoEverything** [comment]
This should not be done how you're doing it. Instead of adding to the count when a property is set, you should add the counts of all the properties when the character count property is accessed. I also feel like the character counts for the individual fields are unnecessary.

**Comment by loukylor** [comment]
> This should not be done how you're doing it. Instead of adding to the count when a property is set, you should add the counts of all the properties when the character count property is accessed.
So if the property returns a value larger than 6000, no error should be thrown?

> I also feel like the character counts for the individual fields are unnecessary.
They're only there to make adding up char count easier.

**Comment by Naamloos** [comment]
I'd argue it's not necessary to return the counts to the user as they'd essentially wont to count the characters themselves. More descriptive exceptions are a nice addition though. You never really know sure where your embed faulted.

**Comment by IDoEverything** [comment]
As of right now, the features in this pull request are pretty useless. If you still want to work on this, then
* Instead of large `get { }` blocks, the counting should be done via single line linq queries that should be fairly simple to come up with.
* There should be exceptions thrown when a message, webhook message, or interaction response has an embed attached where one or more properties or the entire embed exceeds one of discord's limits.

Please make these changes if you're still interested in working on this pr, otherwise it can be closed.

**Comment by loukylor** [comment]
I will go ahead and close it then.

**Pull request closed without merging**
