### PR TITLE
Add configurable string comparison to TextCommandProcessor...

### PR DESCRIPTION
**Pull request by Plerx2493**
for matching command names

# Summary
Adds a `IEqualityComparer<string> CommandNameComparer` to the text command configuration and use it in the processors dictionary

### CODE REVIEW

**Review by akiraveliara — APPROVED** [review]
tested?

**Comment by Plerx2493** [comment]
Not yet

**Comment by TheAlan404** [comment]
literally #1984

**Comment by Plerx2493** [comment]
> tested?

Yes, works

**Pull request merged**
