### PR TITLE
Feature: Support for Gateway Interaction Events

### PR DESCRIPTION
**Pull request by Neuheit**
# Summary
This PR adds support for the gateway events that are fired when a slash command is invoked. 

# Details
This PR does not support creating slash commands, however it aims to support 3rd party extensions until an official version can be released. This comes with the addition of a few slash command types. Additionally, I also ignored the integration events until they become documented by Discord, as there were frequent requests of spamming logging.

I additionally reorganized and grouped many similar entities into their own folders. 

# Changes proposed
* Add support for slash command events (InteractionCreate)
* Add support for a few interaction data types that are sent via gateway
* Ignore integration events for the time being.
* Organize several different entities into folders.

### CODE REVIEW

**Comment by Emzi0767** [comment]
Questions:
- Are we supposed to handle those?
- What exactly do these entail?

**Comment by Soyvolon** [comment]
The `DiscordInteractionDataOption` class will throw a JSON error when a command is run with arguments that are not an integer or choice with an integer value type @Neuheit .

Discord returns a value that is one of the Types defined in [the docs](https://discord.com/developers/docs/interactions/slash-commands#interaction-applicationcommandinteractiondataoption), not the actual type of the value. The `"value"` json parameter should be an `object?`  rather than a `ApplicationCommandOptionType` in order to properly receive data from Discord.

Raw Interaction Create from discord when running a command will all possible option types:
```json
{
   "channel_id":"774408498188386375",
   "data":{
      "id":"793516028608643082",
      "name":"args",
      "options":[
         {
            "name":"choice",
            "value":2
         },
         {
            "name":"age",
            "value":12
         },
         {
            "name":"name",
            "value":"alex"
         },
         {
            "name":"female",
            "value":true
         },
         {
            "name":"user",
            "value":"133735496479145984"
         },
         {
            "name":"channel",
            "value":"752631496376057937"
         },
         {
            "name":"role",
            "value":"750550152141340792"
         }
      ]
   },
   "guild_id":"750486424469372970",
   "id":"793519581104570429",
   "member":{
      "deaf":false,
      "is_pending":false,
      "joined_at":"2020-09-01T22:45:07.036000+00:00",
      "mute":false,
      "nick":null,
      "pending":false,
      "permissions":"2147483647",
      "premium_since":null,
      "roles":[
         
      ],
      "user":{
         "avatar":"27690e2da064e8bdb9c0cef91b2d3a46",
         "discriminator":"8016",
         "id":"133735496479145984",
         "public_flags":131200,
         "username":"Soyvolon"
      }
   },
   "token":"aW50ZXJhY3Rpb246NzkzNTE5NTgxMTA0NTcwNDI5OjRGMVg0d1RCTUphMlZGWEI5c01BeTBNcTVKbENIWlg1dEx1bHd1dHVONlJUVE9pQ0xJZGdaamQ1QmlJMG1rRW5UQjBYanVlMVJ4b0RWVjZHUm9EajVZbjZxS1RxTkllbzFzVnVrenduR1JHdXdSMnZvNXFjUlZ1VExZVVZMbzRl",
   "type":2,
   "version":1
}
```

**Comment by Neuheit** [comment]
> Questions:
> 
> * Are we supposed to handle those?
> * What exactly do these entail?

Yes, this is documented [here](https://discord.com/developers/docs/topics/gateway#interaction-create).
This will allow 3rd party frameworks/bots to use data from the event until we can properly implement it.

**Comment by Neuheit** [comment]
Closing this for now so I can rewrite it to match the latest version.

**Pull request closed without merging**
