### PR TITLE
Adds support for sending file and multiple files with a webhook.

### PR DESCRIPTION
**Pull request by Kiritsu**
# Summary
This pr adds the support for sending single and multiple files with a webhook.

# Details
I tried to follow how it was managed with UploadFilesAsync for user messages.

### CODE REVIEW

**Comment by Kiritsu** [comment]
Sorry for line endings, wasn't doing such crap when editing and commiting in local...

**Comment by Emzi0767** [comment]
Does this build and work as intended? Is the old functionality unaffected?

**Comment by Kiritsu** [comment]
Just found a Null Ref when passing null files (because we check the size of it...) should be fixed in next commit.

**Comment by Kiritsu** [comment]
I also kept my tests in the test bot, but commented them! These tests were all passing as intended

**Pull request merged**
