### PR TITLE
[Code Clean-up] Add Missing XML Doc Param and deal with warnings in code

### PR DESCRIPTION
**Pull request by CloudTheWolf**
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Fixes Missing XML Parameters and cleans up code based on warnings.

# Details
Visual Studio shows a few warning that Either Should Be addressed (Missing XML Doc) or can be supressed.

# Changes proposed
* Add Missing XLM Parameter for WaitForButtonAsync(); 
* Add IDE Suppression For Naming Convention Warnings.
* Simplify If Statements By Converting To Conditional Expressions

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
You could actually drop the tenerary all together and return `new InteractivityResult<ComponentInteractionCreateEventArgs>(result is null, result);`

**Comment by CloudTheWolf** [comment]
@VelvetThePanda 

> You could actually drop the tenerary all together and return `new InteractivityResult<ComponentInteractionCreateEventArgs>(result is null, result);`

Good point, don't how I missed that.

**Comment by VelvetThePanda** [comment]
Out of the scope of this PR but if you wanted you could remove the .Id on the message checks, even though neither message should be null.

**Comment by CloudTheWolf** [comment]
@VelvetThePanda Suggestion Added 😃

**Comment by CloudTheWolf** [comment]
Resolution of Merge Conflicts

**Pull request merged**
